apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: us-central1
  name: solicitedspray-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
        - name: solicitedspray-backend-1
          image: gcr.io/solicitedspray/solicitedspray-backend
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: MONGO_URI
                  key: latest
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: YOUTUBE_API_KEY
                  key: latest
            - name: VIMEO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: VIMEO_ACCESS_TOKEN
                  key: latest
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: REDIS_HOST
                  key: latest
            - name: REDIS_PORT
              value: "17613"
            - name: REDIS_USERNAME
              value: "default"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: REDIS_PASSWORD
                  key: latest
            - name: REDIS_TLS
              value: "false"
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: EMAIL_USERNAME
                  key: latest
            - name: EMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: EMAIL_APP_PASSWORD
                  key: latest
            - name: CONTACT_EMAIL
              value: "estrelloapps@gmail.com"
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: RECAPTCHA_SECRET_KEY
                  key: latest
            - name: AGGREGATE_SECRET
              valueFrom:
                secretKeyRef:
                  name: AGGREGATE_SECRET
                  key: latest
            - name: NODE_ENV
              value: "production"
      vpcAccess:
        connector: projects/solicitedspray/locations/us-central1/connectors/cloudrun-connector
        egress: ALL_TRAFFIC
      serviceAccountName: 615014515729-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
