apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: us-central1
  name: solicitedspray-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
        - name: solicitedspray-backend-1
          image: gcr.io/solicitedspray/solicitedspray-backend
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-uri
                key: latest
          - name: YOUTUBE_API_KEY
            valueFrom:
              secretKeyRef:
                name: youtube-api-key
                key: latest
          - name: VIMEO_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: vimeo-access-token
                key: latest
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-host
                key: latest
          - name: REDIS_PORT
            value: "15108"
          - name: REDIS_USERNAME
            value: "default"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-password
                key: latest
          - name: REDIS_TLS
            value: "false"
          - name: EMAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: email-username
                key: latest
          - name: EMAIL_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: email-app-password
                key: latest
          - name: CONTACT_EMAIL
            value: "estrelloapps@gmail.com"
          - name: RECAPTCHA_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: recaptcha-secret
                key: latest
          - name: AGGREGATE_SECRET
            valueFrom:
              secretKeyRef:
                name: aggregate-secret
                key: latest
          - name: NODE_ENV
            value: "production"
      serviceAccountName: 615014515729-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
